services:
  db:
    image: postgis/postgis:15-3.3
    container_name: fishlog-db
    environment:
      POSTGRES_USER: fishlog
      POSTGRES_PASSWORD: fishlog
      POSTGRES_DB: fishlog
    ports:
      - "5432:5432"
    volumes:
      - fishlog_data:/var/lib/postgresql/data

volumes:
  fishlog_data: